In [1]:
import numpy as np

In [2]:
array = np.array([7,10,4,3,20,15])

In [3]:
array

array([ 7, 10,  4,  3, 20, 15])

In [4]:
for i in range(len(array)):
    for j in range(len(array)-1)
        if i < i+1:
            array[i],array[j] = array[j],array[i]
print(array)
        

SyntaxError: invalid syntax (Temp/ipykernel_19732/1299875206.py, line 2)

In [ ]:
X = [[1, 7, 3],
     [3, 5, 6],
     [6, 8, 9]]
Y = [[1, 1, 1, 2],
     [6, 7, 3, 0],
     [4, 5, 9, 1]]

result = [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]]
import numpy as np
result = np.dot(X,Y)

for r in result:
    print(r)

In [ ]:
a = np.array([10,20,30,40,50])
a

In [ ]:
a[:]

In [ ]:
a[2:]

In [ ]:
a[-1]

In [ ]:
a[-3:-1:]

In [ ]:
a+a

In [ ]:
k = [1,2,3,4]
k+k

In [ ]:
a


In [5]:
a.size

NameError: name 'a' is not defined

In [ ]:
a.shape

In [ ]:
a.std()

In [ ]:
a.var()


In [ ]:
a.min()

In [6]:
a.max()

NameError: name 'a' is not defined

In [7]:
a.itemsize

NameError: name 'a' is not defined

In [8]:
a.dtype

NameError: name 'a' is not defined

In [9]:
l = np.array([1.0,2,4,'A'])

In [10]:
l

array(['1.0', '2', '4', 'A'], dtype='<U32')

In [11]:
l.dtype

dtype('<U32')

In [12]:
np.floor(a)

NameError: name 'a' is not defined

In [ ]:
np.floor_divide?

In [13]:
x = np.array([[1,3,4],[5,6,7]])
x

array([[1, 3, 4],
       [5, 6, 7]])

In [14]:
x.ndim

2

In [15]:
x.shape


(2, 3)

In [16]:
x.size

6

In [17]:
np.zeros(4)

array([0., 0., 0., 0.])

In [18]:
np.zeros((4,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [19]:
np.zeros((2,3,3))

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [20]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [21]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [22]:
np.ones((2,3,4))

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [23]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [24]:
np.eye(4,4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [25]:
#np .eye(3,5,2)
#OR 
np.eye(N=3,M=5,k = 2)

array([[0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [26]:
a = np.identity(4)
a

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [27]:
a.astype(float)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [28]:
a.astype(int)

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

In [29]:
a.__sizeof__()

248

In [30]:
a[1,2] = 5

In [31]:
a

array([[1., 0., 0., 0.],
       [0., 1., 5., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [32]:
np.full((3,4),'NA')

array([['NA', 'NA', 'NA', 'NA'],
       ['NA', 'NA', 'NA', 'NA'],
       ['NA', 'NA', 'NA', 'NA']], dtype='<U2')

In [33]:
np.full((3,4),100)

array([[100, 100, 100, 100],
       [100, 100, 100, 100],
       [100, 100, 100, 100]])

In [34]:
np.linspace(1,100,23)

array([  1. ,   5.5,  10. ,  14.5,  19. ,  23.5,  28. ,  32.5,  37. ,
        41.5,  46. ,  50.5,  55. ,  59.5,  64. ,  68.5,  73. ,  77.5,
        82. ,  86.5,  91. ,  95.5, 100. ])

In [35]:
np.linspace(1,100)

array([  1.        ,   3.02040816,   5.04081633,   7.06122449,
         9.08163265,  11.10204082,  13.12244898,  15.14285714,
        17.16326531,  19.18367347,  21.20408163,  23.2244898 ,
        25.24489796,  27.26530612,  29.28571429,  31.30612245,
        33.32653061,  35.34693878,  37.36734694,  39.3877551 ,
        41.40816327,  43.42857143,  45.44897959,  47.46938776,
        49.48979592,  51.51020408,  53.53061224,  55.55102041,
        57.57142857,  59.59183673,  61.6122449 ,  63.63265306,
        65.65306122,  67.67346939,  69.69387755,  71.71428571,
        73.73469388,  75.75510204,  77.7755102 ,  79.79591837,
        81.81632653,  83.83673469,  85.85714286,  87.87755102,
        89.89795918,  91.91836735,  93.93877551,  95.95918367,
        97.97959184, 100.        ])

In [36]:
np.linspace(1,100).size

50

In [37]:
np.linspace(1,100,retstep=True) 

(array([  1.        ,   3.02040816,   5.04081633,   7.06122449,
          9.08163265,  11.10204082,  13.12244898,  15.14285714,
         17.16326531,  19.18367347,  21.20408163,  23.2244898 ,
         25.24489796,  27.26530612,  29.28571429,  31.30612245,
         33.32653061,  35.34693878,  37.36734694,  39.3877551 ,
         41.40816327,  43.42857143,  45.44897959,  47.46938776,
         49.48979592,  51.51020408,  53.53061224,  55.55102041,
         57.57142857,  59.59183673,  61.6122449 ,  63.63265306,
         65.65306122,  67.67346939,  69.69387755,  71.71428571,
         73.73469388,  75.75510204,  77.7755102 ,  79.79591837,
         81.81632653,  83.83673469,  85.85714286,  87.87755102,
         89.89795918,  91.91836735,  93.93877551,  95.95918367,
         97.97959184, 100.        ]),
 2.020408163265306)

In [38]:
np.linspace(1,100,retstep=True,endpoint=False) 

(array([ 1.  ,  2.98,  4.96,  6.94,  8.92, 10.9 , 12.88, 14.86, 16.84,
        18.82, 20.8 , 22.78, 24.76, 26.74, 28.72, 30.7 , 32.68, 34.66,
        36.64, 38.62, 40.6 , 42.58, 44.56, 46.54, 48.52, 50.5 , 52.48,
        54.46, 56.44, 58.42, 60.4 , 62.38, 64.36, 66.34, 68.32, 70.3 ,
        72.28, 74.26, 76.24, 78.22, 80.2 , 82.18, 84.16, 86.14, 88.12,
        90.1 , 92.08, 94.06, 96.04, 98.02]),
 1.98)

In [39]:
np.arange(1,122,0.5)

array([  1. ,   1.5,   2. ,   2.5,   3. ,   3.5,   4. ,   4.5,   5. ,
         5.5,   6. ,   6.5,   7. ,   7.5,   8. ,   8.5,   9. ,   9.5,
        10. ,  10.5,  11. ,  11.5,  12. ,  12.5,  13. ,  13.5,  14. ,
        14.5,  15. ,  15.5,  16. ,  16.5,  17. ,  17.5,  18. ,  18.5,
        19. ,  19.5,  20. ,  20.5,  21. ,  21.5,  22. ,  22.5,  23. ,
        23.5,  24. ,  24.5,  25. ,  25.5,  26. ,  26.5,  27. ,  27.5,
        28. ,  28.5,  29. ,  29.5,  30. ,  30.5,  31. ,  31.5,  32. ,
        32.5,  33. ,  33.5,  34. ,  34.5,  35. ,  35.5,  36. ,  36.5,
        37. ,  37.5,  38. ,  38.5,  39. ,  39.5,  40. ,  40.5,  41. ,
        41.5,  42. ,  42.5,  43. ,  43.5,  44. ,  44.5,  45. ,  45.5,
        46. ,  46.5,  47. ,  47.5,  48. ,  48.5,  49. ,  49.5,  50. ,
        50.5,  51. ,  51.5,  52. ,  52.5,  53. ,  53.5,  54. ,  54.5,
        55. ,  55.5,  56. ,  56.5,  57. ,  57.5,  58. ,  58.5,  59. ,
        59.5,  60. ,  60.5,  61. ,  61.5,  62. ,  62.5,  63. ,  63.5,
        64. ,  64.5,

In [40]:
np.random.random(5)

array([0.46742438, 0.68373133, 0.82004121, 0.78401192, 0.20344757])

In [41]:
np.random.rand(5)

array([0.61735916, 0.43883537, 0.22652957, 0.55133391, 0.37576282])

In [42]:
np.random.randint(15)

5

In [43]:
np.random.randint(3,10,size = (3,4))

array([[5, 7, 4, 9],
       [6, 7, 3, 4],
       [8, 7, 4, 5]])

In [44]:
~np.ones((3,4),dtype = bool)

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [45]:
a

array([[1., 0., 0., 0.],
       [0., 1., 5., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [46]:
a.T

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 5., 1., 0.],
       [0., 0., 0., 1.]])